Resources:
  tollHistory:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: byUserIdDate
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: byUserIdDeviceId
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: deviceId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

      KeySchema:
        - AttributeName: deviceId
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: deviceId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        # - AttributeName: entryId
        #   AttributeType: S
        # - AttributeName: exitId
        #   AttributeType: S
        # - AttributeName: fee
        #   AttributeType: N

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false # we are cheap and don't want to pay for backups (yet)

  users:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        # - AttributeName: deviceId
        #   AttributeType: A

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false # we are cheap and don't want to pay for backups (yet)

  chargeMaster: # this is a list of all the tolls and their prices
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: entryId
          KeyType: HASH
        - AttributeName: exitId
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: entryId
          AttributeType: S
        - AttributeName: exitId
          AttributeType: S
        # - AttributeName: fee
        #   AttributeType: N

      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: false # we are cheap and don't want to pay for backups (yet)
