service: e-toll

provider:
  stage: prod
  name: aws
  region: eu-central-1
  runtime: provided.al2
  stackTags:
    project: e-toll
    type: code-challenge
    stage: prod

plugins:
  - ./vendor/bref/bref

functions:
  - ${file(src/tollCommunication/tollCommunication.yml)}

resources:
  - ${file(db.yml)}
  - ${file(src/tollCommunication/tollCommunicationRole.yml)}

# Exclude files from deployment
package:
  patterns:
    - "!tests/**"
